### PR TITLE
Add monostate support as a nullptr

### PR DESCRIPTION
**Pull request by epsilon-phase**
Adding a option for the database binding operator to take `std::monostate` as a `nullptr` simplifies my code significantly. It also seems to me that it's a fairly straightforward semantic.

### CODE REVIEW

**Comment by aminroosta** [comment]
> **std::monostate** Unit type intended for use as a well-behaved empty alternative in std::variant

@epsilon-phase I agree, i think binding `nullptr` in this case makes sense.
Few things before we merge this:

- [ ] please send this PR to `dev` branch instead
- [ ] add a line to the docs explaining this feature (in readme file where std::variant is mentioned).
- [ ] write a unit test for it (in dev branch unit tests are much easier to work with).

**Comment by epsilon-phase** [comment]
Oh, Okay. Sure.

**Comment by epsilon-phase** [comment]
Oh... Wow

This is very different

**Comment by epsilon-phase** [comment]
Let's call this a mulligan, give me a bit for the test though :)

**Pull request closed without merging**
